language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t psthree/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true psthree/react-test npm tes

after_success:
  - docker build -t psthree/multi-client ./client
  - docker build -t psthree/multi-nginx ./nginx
  - docker build -t psthree/multi-server ./server
  - docker build -t psthree/multi-worker ./worker
  #login to Docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # push these images to docker hub
  - docker push psthree/multi-client
  - docker push psthree/multi-nginx
  - docker push psthree/multi-server
  - docker push psthree/multi-worker
